---
title: "Bio326.popgen"
author: "Marie Saitou"
date: "4/26/2021"
output: html_notebook
---

# Simulating of evolution/Visualization with ggplot2
# https://bookdown.org/yihui/rmarkdown/notebook.html#using-notebooks

[as Rmarkdown](https://github.com/mariesaitou/Bio326/blob/master/docs/assets/BIO326-misc/popgen.simu.Rmd)

# Get started
Go to:
https://orion.nmbu.no/ -> JupyterHub, select 4Gb -> rstudio-4.0.2



```{bash, eval=FALSE}

#copy the file from /net/fs-1/home01/mariesai/BIO326/popgen.simu.Rmd
cp /net/fs-1/home01/mariesai/BIO326/popgen.simu.Rmd .
```


# Data Preparation 
```{r prep}

rep=50  # number of simulations
n_gen=100 # number of generations

generation <-  1
n_AA <-  99 # number of newborn individual with AA genotype
n_AB <-  1  # number of newborn individual with AB genotype
n_BB <-  0 # number of newborn individual with BB genotype
N <-  n_AA + n_AB + n_BB # total number of individuals

sAA <-  0 # advantage AA genotype
sAB <-  0 # advantage AB genotype
sBB <-  0 # advantage BB genotype

results <- data.frame(matrix(ncol = 7, nrow = 0)) # dataframe to put the results in

```

# Run simulation
```{r }
for (i in 1:rep){
  # initialize
  next_num <- c(n_AA, n_AB, n_BB)
  freqA <-  (2 * next_num[1] + next_num[2]) / (2 * N) 
  freqB <-  1 - freqA
  results <- rbind(results, c(i, 0, next_num, freqA, freqB))
  
  for (j in 1:n_gen){

    # effective frequency of allele after survival
    freqA <- ((2 * next_num[1]*(1 + sAA) + next_num[2] * (1 + sAB)) /
                (2 * (next_num[1] * (1 + sAA) + next_num[2] * (1 + sAB) + next_num[3] * (1 + sBB)))) # frequency of A allele in the population
    freqB <-  1 - freqA # frequency of B allele in the population
    
    # next generation
    next_num <- c(rmultinom(1, N, c(freqA * freqA, 2 * freqA * freqB, freqB * freqB)))
    
    # new frequency of allele
    freqA <-  (2 * next_num[1] + next_num[2]) / (2 * N) # frequency of A allele in the population
    freqB <-  1 - freqA

    results <- rbind(results, c(i, j, next_num, freqA, freqB))
    
  }
  
}

names(results) <- c("rep", "gen", "AA", "AB", "BB", "freqA", "freqB")
```


# View results
```{r}
head (results)
```
# View the allele frequency change in generations
```{r plot1}
# plot two figures
library(tidyverse)
library(ggplot2)

# color=group, if the last freqA is 0 or 1, highlight them.
ggplot(results, aes(gen, freqB, group = rep)) + geom_line()+theme_bw()
```

# View the final genotype frequency
```{r plot2}
# [plot2] 
# results_sum <- data.frame(cbind(c("AA", "AB", "BB"), 
# colMeans(results[results$gen==n_gen,c("AA", "AB", "BB")]))) %>%
#   mutate(x="proportion", X2 = as.numeric(X2))

# gen is the generation we want to see
results_sum <- pivot_longer(results[results$gen == n_gen,c("rep", "AA", "AB", "BB")], 
                            cols=c("AA", "AB", "BB"), names_to="genotype", values_to="count")

ggplot(results_sum, aes(x=rep, y=count, fill=genotype)) +
  geom_col() +theme_bw()

```

